### PR TITLE
Fix double-processing of kmers

### PR DESCRIPTION
**Pull request by edawson**
Adds a switch to not preprocess composed seq kmers if a k of zero is passed

### CODE REVIEW

**Review by brentp — CHANGES_REQUESTED** [review]
can you rebase this onto eric-saves-the-day branch?

**Comment by edawson** [comment]
> 
> 
> can you rebase this onto eric-saves-the-day bran

**Comment by edawson** [comment]
Rebased

**Comment by edawson** [comment]
Which branch do we want to merge it into? Still main?

**Comment by brentp** [comment]
maybe into your namesake

**Comment by edawson** [comment]
Recombination by git. Branch based.

**Pull request merged**
